server:
  port: 8081
spring:
  main:
    banner-mode: off
  data:
    elasticsearch:
      repositories:
        enabled: true
  kafka:
    consumer:
      bootstrap-servers:
        - localhost:9092
      group-id: my-group
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 5
      heartbeat-interval: 3
      properties:
        session.timeout.ms: 10
elasticsearch:
  hostname: nath-course-8789992670.us-east-1.bonsaisearch.net
  user-key: ${user-key}
  user-secret: ${user-secret}
  index: twitter
  type: tweets
