spring:
  main:
    banner-mode: off
  social:
    twitter:
      app-id: ${twitter-app-id}
      app-secret: ${twitter-api-secret}
      access-token: ${twitter-access-token}
      access-secret: ${twitter-access-secret}
  kafka:
    producer:
      bootstrap-servers:
        - localhost:9092
      client-id: producer-1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      enable-idempotence: true
      acks: all
      compression-type: snappy
      batch-size: 100KB
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        linger.ms: 500